- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/send_events.rb
- lib/dfe/analytics/testing/helpers.rb
- spec/requests/analytics_spec.rb
Clients can now configure the ActiveJob queue name, plus the BigQuery timeout and retry count options.
> Add config options: queue name, BQ timeout, BQ retries

- config/event-schema.json
- lib/dfe/analytics/send_events.rb
This is now one-size-fits-all for BAT services. It has some extra Apply-only bits (ie `namespace`) — we can tidy that up if we ever want to.
As schemas in BQ might lack fields we now send, this PR adds `ignore_unknown` to the inserts, which makes the client silently drop fields instead of throwing exceptions. If and when schemas are standardised in BQ (we can in fact generate BQ schemas from the JSON) we can tighten this up again.
> Standardise event-schema.json

- README.md
- lib/generators/dfe/analytics/install_generator.rb
This doesn't make any difference in practice, but it will save new clients the trouble of renaming this file to appease Rubocop
> Use snake_case for config file

- lib/dfe/analytics/load_entities.rb
- spec/dfe/analytics/load_entities_spec.rb
When using batch size or sleep time from load entities (`bundle exec rails dfe:analytics:import_entity[ModelName,1,1,1]` rake task it raises the exception:
String can't be coerced into Integer
(Refer to
https://ukgovernmentdfe.slack.com/archives/CN1MCQCHZ/p1654509372363969)
By converting the values we guarantee that it will work as expected.
> Fix rake task when using arguments

- Gemfile
- Gemfile.lock
- dfe-analytics.gemspec
It's not a direct dependency — it's only necessary for executing the code in an environment where Rails isn't present.
**Depends on #9**
> Make Rails a development_dependency

- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
- spec/requests/analytics_spec.rb
> Don't crash on invalid UTF-8 in headers

- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
- spec/spec_helper.rb
When converting event data into the JSON payload to send to BQ, we used
to selectively only convert Hash values to JSON with "to_json". However,
some data values passed through for sending to BigQery may not present as a
Hash, e.g. trainees.progress in Register, causing inseration errors in
BQ.
This change makes us more lenient and will try to convert any value to
JSON if it implements the "to_json" method.
> convert data values using to_json

- README.md
- lib/dfe/analytics/testing.rb
- spec/dfe/analytics/send_events_spec.rb
This makes two changes to the built-in testing modes to make them easier to use:
- Fixes a bug where `fake!` currently doesn't work as the stubbed `insert` method has the wrong signature.
- Adds a paragraph in the documentation explaining how to use the testing modes.
> Improve testing modes

- .rubocop.yml
- README.md
- lib/dfe/analytics.rb
- lib/dfe/analytics/event.rb
- lib/dfe/analytics/fields.rb
- lib/dfe/analytics/load_entities.rb
- lib/dfe/analytics/tasks/fields.rake
- lib/dfe/analytics/tasks/import_entities.rake
- spec/dfe/analytics/fields_spec.rb
- spec/dfe/analytics/load_entities_spec.rb
- spec/dfe/analytics_spec.rb
The useful `analytics:check` task detects when we add and remove fields from applications, but it had a shortcoming: it couldn't tell when a field existed in both the allowlist and the blocklist. This wasn't considered first time around because _why would that ever happen_. We now know that it _does_ happen, and it happens when an entity wasn't previously in the allowlist but was in the blocklist (because we ignored it), and now we've added it to the allowlist (because we've decided not to ignore it) and now it's appearing in both.
Not necessarily a problem, but it's unprofessional and confusing and it looks bad so it's no longer allowed 🚫 .
This PR also contains some refactoring to the README and methods which refer to the word `model`. We don't believe in `models` out here; we believe …
> Refactor to straighten out language and improve dfe:analytics:check

- lib/dfe/analytics/requests.rb
- spec/dummy/app/controllers/application_controller.rb
Some services may declare `current_user` (or `current_*` really) as private methods if there is no need to expose that method in the controller. Previously we would miss out on sending the `user_id` with the event if this was the case, this change allows us to detect these as private methods.
For testing purposes, we've made the `current_*` methods private since that ensures we work with both private and public versions of these methods.
> detect private current_* methods

- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
We've previously added special handling to event data processing for objects that can be converted to JSON; this change expands that to handle an array of these objects that can be converted to JSON. Words are hard, a ~~picture~~JSON structure is worth a thousand words:
BEFORE BAD:
```json
{
"key": "accrediting_provider_enrichments",
"value": [
{
"UcasProviderCode": "N21",
"Description": "",
"validation_context": null,
"errors": {
}
}
]
}
```
NOW GOOD:
```json
{
"key": "accrediting_provider_enrichments",
"value": [
"{\"UcasProviderCode\":\"N21\",\"Description\":\"\",\"validation_context\":null,\"errors\":{}}"
]
}
```
(we now encode each element of the array to JSON).
This has change has also been tested in the test environment.
> [770] handle arrays of JSON-friendly objects

- Gemfile.lock
- lib/dfe/analytics/tasks/import_entities.rake
Tried to run one of the rake tasks in Publish and it was complaining about structure of args. This PR introduces a couple of fixes:
- Fixes rake task `:import_all_entities`, eg:
```ruby
NameError: undefined local variable or method `entities_for_analytics' for main:Object
entities_for_analytics.each do |entity_name|
```
- Fixes rake task `:import_entity` to correctly destructure args otherwise we get:
```ruby
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: entity_name)
```
- Pins async gem to a version that hasn't been yanked
Also pinned the async gem to a version that hasn't been yanked, let me know if this is ok.
> Fix rake tasks

- README.md
- lib/dfe/analytics.rb
- lib/dfe/analytics/fields.rb
- lib/dfe/analytics/railtie.rb
- lib/dfe/analytics/tasks/fields.rake
- spec/dfe/analytics/entities_spec.rb
- spec/dfe/analytics/fields_spec.rb
- spec/dfe/analytics/load_entities_spec.rb
- spec/dfe/analytics_spec.rb
- spec/requests/analytics_spec.rb
- spec/spec_helper.rb
See commits.
Manually mixing the behaviour in to ActiveRecord classes does not achieve what we want to achieve: it missed out HABTM relations. So hook up everything automatically — `analytics.yml` will determine what gets sent. As part of this piece of work we now refuse to boot if that file isn't correct, which should surface configuration issues as early as possible.
Depends on #36.
> Initialize model callbacks on boot

- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
- spec/dfe/analytics_spec.rb
Some systems may not be able to, or prefer not to, use the id attribute
on user to identify the user. Allow these systems to call a different
method on the user to return an identifier.
This change should not break existing systems as defaults to using `user.id` as the previous systems did.
> allow user id field to be configurable

- lib/dfe/analytics/load_entities.rb
- lib/dfe/analytics/load_entity_batch.rb
- spec/dfe/analytics/load_entity_batch_spec.rb
ActiveJob < 6.1 cannot handle classes in params
"Allow Class and Module instances to be serialized." appeared in
Rails changelog at https://github.com/rails/rails/releases/tag/v6.1.0.rc1
Fixes https://trello.com/c/nLQjJ9YM/816-blocks-claim-onboarding-class-serialisation-error-during-dfe-analytics-backfill
> Pass model names as strings when loading batches

- lib/dfe/analytics/railtie.rb
- lib/dfe/analytics/send_events.rb
- lib/generators/dfe/analytics/install_generator.rb
It was necessary to defer setting the logger to after ActiveJob had loaded, because ActiveJob sets a logger in its own Railtie.
https://github.com/rails/rails/blob/a5018cf149d47e1aed1e74dd35e4d519b507c364/activejob/lib/active_job/railtie.rb#L13-L15
> Change ActiveJob log level

- README.md
- Rakefile
This change allows us omit PRs labeled with `version-release` from the automatically generated `CHANGELOG.md` file. This just makes the changelog slightly tidier and is purely cosmetic.
> ignore version release PRs in changelog

- .gitignore
- lib/dfe/analytics/event.rb
- lib/dfe/analytics/load_entities.rb
- lib/dfe/analytics/load_entity_batch.rb
- lib/dfe/analytics/testing.rb
- spec/dfe/analytics/load_entities_spec.rb
- spec/dfe/analytics/load_entity_batch_spec.rb
Objectives:
- don't overflow queues
- don't hit BQ byte limits
Hopefully this isn't too complicated.
Still to do: find out the actual byte limit and set it
> Make backfill resilient

- lib/dfe/analytics/load_entities.rb
- spec/dfe/analytics/load_entities_spec.rb
We can probably handle these, but it would involve fixing find_in_batches to work with non-id PKs, which is out of scope for now
> Ignore models with non-id primary keys

- lib/dfe/analytics.rb
- spec/dfe/analytics_spec.rb
4️⃣   error conditions we discovered during recent rollout in Publish and Apply CI pipelines.
- ActiveRecord::SchemaMigrations table is being considered for dfe-analytics (ignore it)
- discovering migrations pending on dfe-analytics init
- discovering missing database connection when database not present, also on init
- loading models (in init) before connecting to DB
The final example is important because some contexts which lack db connections (eg asset precompilation) also don't provide all necessary eg ENV vars which would be required were we loading the whole app (which this init process does).
So discover early if we have no database (call `ActiveRecord::Base.connection`). & if anything happens during Fields.check! catch that too. Log lines will tell us if we're bailing for want of …
> 🍀 Four kinds of init error

- lib/dfe/analytics.rb
- spec/dfe/analytics_spec.rb
- spec/spec_helper.rb
And another build-related edge case 😅 
Manually throw a MigrationPending exception, or else, in cases where app code begins executing before migration has run (eg worker instances that override default Docker entrypoints) and there is no DB schema yet (eg review apps), we get an error saying that the whole schema needs to be put into the blocklist
> Recover when the database hasn’t been set up yet

- Rakefile
We've had some issues with versions not being added correctly because, really, github_changelog_generator is a bit rough around the edges and very peculiar. These instruction will hopefully help with that.
> add instructions before pushing

- README.md
- lib/dfe/analytics/send_events.rb
DfE::Analytics::SendEvents expects an array of hashes. This change allows passing constructed DfE::Analytics::Event object as well, without need to convert them into hashes first.
> Custom events

- README.md
- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
[Trello-975](https://trello.com/c/Q9WmHE1g/1004-teaching-vacancies-userid-field-is-blank-in-events-table-not-sure-how-to-configure-this-in-dfe-analytics)
Add anonymisation of user_id in the web request event data
- Make this configurable through dfe analytics config
- Update README to explain anonymisation and custom user identifier
> Add anonymisation of user_id in the web request event data

- README.md
- lib/dfe/analytics.rb
- lib/dfe/analytics/event_matcher.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/event_matcher_spec.rb
- spec/dfe/analytics/send_events_spec.rb
[Trello-975](https://trello.com/c/rUufn40w/975-investigate-silent-failures-in-dfe-analytics)
Create an events filter for logging, so that we log only the events of interest. This will allow targeted logging for diagnostic and debugging purposes.
The events filter is held in a YAML config.
Event filter example:
``` Yaml
#
#
#
#
#
#
shared:
event_filters:
-
type: (create|update|delete)_entity
entity_table_name: course_options
data:
key: id
value: 12345
```
> Log Matched Events

- README.md
[Trello-887](https://trello.com/c/lUFIEQhg/887-add-more-advice-to-dfe-analytics-documentation)
Add following advice to README.md:
- Don't run a backfill when you've got a lot of traffic
- Make sure you have a dedicated worker for BQ
> Update advice on queue config and running imports

- README.md
- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/middleware/send_cached_page_request_event.rb
- lib/dfe/analytics/railtie.rb
- spec/dfe/analytics/middleware/send_cached_page_request_event_spec.rb
- spec/dfe/analytics/requests_spec.rb
[Trello-1058](https://trello.com/c/6b49g4yk/1058-bug-git-website-home-page-views-in-ga-much-greater-than-in-events-table-in-bq)
We have a big inconsistency tracking homepage visits on the GiT website through BigQuery.
BQ Count: 1637 vs GA Count: 65,263. Please see ticket for details.
After some troubleshooting we found that there is page caching of static pages, the homepage being a static page.
GiT website uses [rack-page_caching](https://github.com/pkorenev/rack-page_caching) GEM, that implements caching through rack middleware.
The DfE Analytics syncs web request events with a controller after action callback.
Cached pages are served by rack middleware, returning early and therefore do not execute any actions in the controller. This means that any cached page visits handled by rack …
> Send request events for cached pages with rack middleware

- lib/dfe/analytics/railtie.rb
- spec/spec_helper.rb
[Trello-1107](https://trello.com/c/fBBPetwX/1107-refer-serious-misconduct-apply-for-qts-unable-to-upgrade-to-latest-dfe-analytics-gem)
The problem is mainly seen during the rails assets:precompile step while the docker container is being built. This article [here](https://glennjon.es/2022/07/02/fixing-no-such-middleware-to-insert-before-error-during-docker-build.html)  explains it well:
Three options considered to address the problem:
1. Set env variable `RAILS_SERVE_STATIC_FILES=true` for precompile in the Dockerfile:
For example:
```
RUN RAILS_SERVE_STATIC_FILES=true SECRET_KEY_BASE=dummyvalue rails assets:precompile
```
2. Catch the Ruby run time error on the insert middleware and ignore if it matches the expected error message.
For example:
```
begin …
```
> Refer serious misconduct / Apply for QTS unable to upgrade to DfE Analytics GEM (v1.8.0)

- README.md
- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/event.rb
- lib/dfe/analytics/initialise.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/entities_spec.rb
- spec/dfe/analytics/event_spec.rb
- spec/dfe/analytics/initialise_spec.rb
- spec/dfe/analytics_spec.rb
- spec/requests/analytics_spec.rb
- spec/spec_helper.rb
[Trello-1168](https://trello.com/c/KKNNGzR9/1168-dfe-analytics-gem-send-system-config-event)
Send dfe analytics version and required config items from DfE Analytics to BigQuery as an "analytics_initialise" event.
The "analytics_initialise" is a one-off on startup event.
Also, some miscellaneous READ.me updates:
- Document the anonymise data method available
- A further information and instructions on pushing tags
> Send config events

- lib/dfe/analytics.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/send_events_spec.rb
Currently when doing a full import on the Teaching Vacancies App, calls to the BigQuery insert API are failing.
There are very few clues in the error logs as to which events are causing the failures. As the full import calls the BigQuery insert API in batches of 500, it's also very difficult to pinpoint the event causing the failure.
This PR adds better error logging when calling the API and logs the events causing the failures also.
> Add better error logging when calling BigQuery insert API on error

- Gemfile.lock
- dfe-analytics.gemspec
- lib/dfe/analytics.rb
- lib/dfe/analytics/fields.rb
- lib/dfe/analytics/load_entities.rb
- spec/dfe/analytics/single_table_inheritance_spec.rb
When apps use single-table inheritance, multiple Rails models share the same database table - i.e. they are considered a single 'entity' by DfE Analytics.
This isn't good, because it means that at most one model can be associated with a single table. In turn this means that we will not know to attach callbacks to the other models in the STI heirarchy. In practice, due to the order in which `ActiveRecord::Base.descendants` returns the models, this ends up being the alphabetically first child — not the parent, and not any of the siblings.
~Added DNM so @JR-G can test it out on Apply first!~
Confirmed working on Apply
> Support single table inheritance

- lib/dfe/analytics/tasks/fields.rake
- lib/generators/dfe/analytics/templates/fields_spec.rb
When going through the gem's codebase, I noticed a couple of places where the wording was incorrect or needed to be upgraded:
- Wrong task description matching another rake task.
- A command message displaying a deprecated interface call for a rake task.
> Minor wording fixes

- README.md
[Trello-975](https://trello.com/c/rUufn40w/975-investigate-silent-failures-in-dfe-analytics)
When an error occurs in `DfE::Analytics::SendEvents` calling the events insert API, the error responses are logged, but the events that caused the error are not included in the log message.
Add the events to the error log message to help with error diagnosis.
Also add advice for event debugging regarding sensitive data.
> Add event details to send event error log message

- lib/dfe/analytics/railtie.rb
db:* rake commands are often useful to bring the database into line with what DfE::Analytics expects, so it can be painful not to be able to run them when the config is inconsistent. Allow these commands at all times - full checks will run on app or test boot anyway.
I couldn't think of a reasonable way to test this!
> Do not attempt initialization when the user is changing the database

- lib/dfe/analytics.rb
- spec/dfe/analytics/single_table_inheritance_spec.rb
This fix prevents the deprecation warning `Entities was manually included in a model` from being raised when using single table inheritance. The warning was being raised because the `DfE::Analytics::Entities` module gets included in all the entity model classes.
I noticed we were still getting deprecation warnings after this PR got merged: https://github.com/DFE-Digital/apply-for-teacher-training/pull/8374
```shell
DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (ApplicationWorkExperience), but it's included automatically since v1.4. You're running v1.10.1. To silence this warning, remove the include from model definitions in app/models.
DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (ApplicationVolunteeringExperience), but …
```
> Fix single table inheritance deprecation warning bug

- lib/dfe/analytics/fields.rb
- spec/dfe/analytics/fields_spec.rb
When the application has models that are configured with single table inheritance the generated blocklist will contain duplicate field names for the table (once for each model).
This is due to the behaviour of `attribute_names` in Rails; it retrieves the names directly from the table columns and doesn't filter based on the context of the subclass.
To avoid this we need to `uniq` the attribute names generated for the blocklist.
Example blocklist prior to change (assuming a parent/child using STI):
```
{:with_model_candidates_43990_9360=>["id", "first_name", "id", "first_name"]}
```
And after change:
```
{:with_model_candidates_43990_9360=>["id", "first_name"]}
```
> Prevent duplicate fields in blocklist when using STI

- README.md
- lib/dfe/analytics/load_entities.rb
- spec/dfe/analytics/load_entities_spec.rb
`dfe-analytics` does not load entities if they do not have a primary key. This issue was discovered when ECF (CPD) were installing the gem and were unable to load a join table which did not have a primary key.
It was decided to update the error messaging / readme to ask that a primary key to be added to the entity in these situations.
This PR includes these additions (1. update to logging message 2. update to README.rb)
Updates to the loading strategy, to make it more robust, will be considered in future.
> Add log message for entities without primary_key, update README.rb

- lib/dfe/analytics.rb
- spec/dfe/analytics/entities_spec.rb
On ECF installation and set up of `dfe-analytics` - it was noticed that not all values of three columns were being sent to dataform (`mentor_profile_id`, `school_cohort_id` and `school_id`). On investigation it was noticed that these values are listed as `ignored_columns` on the children classes in a STI relationship in ECF (but not on the parent).
The updates in this PR are to add hidden_columns to attributes and to allow nil values to be sent to dataform.
> Add ignored_columns to attributes

- README.md
- lib/dfe/analytics/entity_table_check_job.rb
- lib/dfe/analytics/initialisation_events.rb
- spec/dfe/analytics/entity_table_check_job_spec.rb
- spec/dfe/analytics/initialisation_events_spec.rb
- spec/requests/analytics_spec.rb
The previous iteration of this was low maintenance self-scheduling but when tested on Register, it was not scheduling properly. 
This iteration is for services who have Sidekiq and Sidekiq cron already installed (or who want to install them). 
Syntax is updated to work with Sidekiq and README.rb is updated to give instructions on how to set up the job.
Services will have more control over scheduling and the job will be more reliable.
> Update scheduling for Entity Table Check Job

- lib/dfe/analytics/entity_table_check_job.rb
- spec/dfe/analytics/entity_table_check_job_spec.rb
If the production database is Postgres, to speed up the query, the entity table data / checksum lookup is updated to be entirely in SQL so that it is executed within the db. This will reduce the memory burden on Rails and also prevent the retrieval of a large number of IDs. 
It was necessary to keep the original Active Record lookup given that the test db is SQLite3 and the updated SQL is incompatible.
> Update lookup to SQL if postgres db

- Gemfile.lock
- dfe-analytics.gemspec
- lib/dfe/analytics/entity_table_check_job.rb
- spec/dfe/analytics/entity_table_check_job_spec.rb
- spec/spec_helper.rb
We noticed after testing on Register, that the entity_check_job would loop through sub-types causing an extra event to be sent to BQ.
This PR updates the perform method to loop through entities only and updates the build_event_for method to handle entity_name rather than model. The logger message had to be moved too.
> Update entity_check_job to loop through entities only

- lib/dfe/analytics/analytics_job.rb
This method is deprecated in Rails 7.1 and will be removed in Rails 7.2.
https://github.com/rails/rails/blob/7-1-stable/activejob/CHANGELOG.md#rails-710rc1-september-27-2023
> Update deprecated exponentially_longer method

- lib/dfe/analytics.rb
- spec/dfe/analytics/entities_spec.rb
This fix was introduced to assist ECF with a STI bug where different ignored_columns on different child models (with the same parent) were not being sent to BigQuery.
The fix wasn't working all of the time and in the end the simplest solution was to remove reference to the ignored_columns in the child models so that all of the fields are being sent all of the time.
It is probably confusing to keep this code in dfe-analytics and it is unlikely to be needed by another service because usually when a column is ignored there would not be a requirement to send it to Big Query.
> Remove fix for ignored columns

- lib/dfe/analytics/entity_table_check_job.rb
- spec/dfe/analytics/entity_table_check_job_spec.rb
Not all entity tables have updated_at columns. 
It is necessary to have fallback columns to order by. This PR allows the checksum lookup to be ordered by updated_at then created_at and finally the ID if the other two don't exist.
> Checksum ordered by update

- lib/dfe/analytics/entity_table_check_job.rb
- spec/dfe/analytics/entity_table_check_job_spec.rb
We are now dynamically finding the order by column for the entity since sometimes updated_at is missing.
Instead of only checking the model for the existence of the order_by fields, we are now ensuring that they exist in the analytics.yml.
The logic has been updated so that we are from within the determine_order_column method ->
1) finding the entity keys on the allow list
2) returning unless an order column exists i.e. whether updated_at / created_at / id exists in the analytics.yml
3) adding an additional check that the column exists both on the model and in the analytics.yml
> Ensure order by column is in analytics.yml

- CHANGELOG.md
- Gemfile.lock
- lib/dfe/analytics/version.rb
This update ensures that the checksum lookup only uses order_by values that exist in the analytics.yml (instead of looking to the model for their presence)
It also removes ordering by ID although this may be reintroduced at a later stage.
> Release v1.11.6

- lib/dfe/analytics/entity_table_check_job.rb
Teaching vacancies use PostGIS as a db which extends the capabilities of the PostgreSQL.
The Entity Table check job is not running for them on their review app as it point to production and the adapter_name is postgis. In production the job also won't run because the conditional returns false unless it is postgres in production.
This PR updates the conditional so that the job will run if the adapter_name is postgis. This shouldn't cause any issues as postgis is an extension of postgres and so the lookup should run as it would on postgres
> Update conditional to handle 'postgis' db

- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
This changes the event to get the request path from the `original_fullpath` method rather than the `path` method. I'm making this change as the `original_fullpath` represents the path of the page as requested by the user, not necessarily the page being rendered.
In most cases the original path and the path will be the same, but there are some scenarios where it is. Specifically, when rendering a custom error page in Rails which is mounted at `/404` the path ends up being the value `/404` rather than the path which triggered the 404 page.
> Use original_fullpath for request path

- config/locales/en.yml
- lib/dfe/analytics.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/send_events_spec.rb
- spec/dfe/analytics_spec.rb
Relating to this [ticket ](https://trello.com/c/LacYDk5E/1802-dfe-analytics-support-scheduled-downtime-for-bigquery)
We need the ability to do maintenance on on a live streamed BiqQuery dataset, such as register_events_production.
This PR adds a configuration item for a maintenance window.
Redis logic - WIP
- On reaching the start maintenance window start timestamp, DfE Analytics will start queueing items with a schedule time of:
end_timestamp + number of seconds elapsed since start_timestamp
The queued items will end up queued in Redis.
- Once the end of the maintenance window is reached, the queue items will be processed and sent to BigQuery and a First In First Out (FIFO) base.
> Add maintenance window logic

- lib/dfe/analytics/entities.rb
An error was observed on ECF as the event tag is nil in the context of a create event. Removing the array brackets from the event tag in the entities file should prevent this - although a longer term solution will need to be found.
> Remove array brackets for unused event tag

- lib/dfe/analytics/services/generic_checksum_calculator.rb
- lib/dfe/analytics/services/postgres_checksum_calculator.rb
- lib/dfe/analytics/shared/checksum_query_components.rb
- spec/dfe/analytics/services/entity_table_checks_spec.rb
This PR attempts to fix an issue we have with periodic mismatching of checksums - which might be arising due to a lack of enforced ordering
> Add order by clause to ensure consistent ordering

- lib/dfe/analytics/services/postgres_checksum_calculator.rb
In the latest re-factoring, 'as checksum' was omitted and this stopped checksums from pulling through. This PR fixes that.
> Re-add 'as checksum'

- README.md
- Rakefile
This PR updates our release process to manually tag the release after the release PR has been merged into main. This should mean the tag references the correct commit and makes it more likely that Depandabot finds the new release without erroring.
> Update release instructions relating to tagging

- spec/dfe/analytics/services/entity_table_checks_spec.rb
We are getting flakey tests in this file with the checksum_calculated_at being 1s after the expectation. This PR 
- Updates `@checksum_calculated_at` to store a Time object instead of a 
string to ensure compatibility with Timecop.freeze
- Modifies the before block to fetch current_timestamp from the database, 
convert it to the specified timezone, and directly use this Time object 
with Timecop.freeze
- Ensure Timecop is used effectively by freezing time at the exact 
moment defined by the database's current timestamp in the specified 
timezone
> Fix for flakey tests

- lib/dfe/analytics.rb
- lib/dfe/analytics/entities.rb
- lib/dfe/analytics/event.rb
- lib/dfe/analytics/fields.rb
- lib/dfe/analytics/initialisation_events.rb
- lib/dfe/analytics/load_entity_batch.rb
- lib/dfe/analytics/services/entity_table_checks.rb
- spec/dfe/analytics/entities_spec.rb
- spec/dfe/analytics/event_spec.rb
- spec/dfe/analytics/fields_spec.rb
- spec/dfe/analytics/load_entity_batch_spec.rb
- spec/dfe/analytics_spec.rb
[Ticket](https://trello.com/c/IpCySdeH/1879-populate-datahidden-field-in-streamed-events) 
This PR introduces a with_hidden_data event field
Hidden data is kept separate to both allowed_data and allowed_pii
> Allow hidden data to be sent separately

- Gemfile.lock
- config/locales/en.yml
- dfe-analytics.gemspec
- lib/dfe/analytics.rb
- lib/dfe/analytics/azure_federated_auth.rb
- lib/dfe/analytics/big_query_api.rb
- lib/dfe/analytics/big_query_legacy_api.rb
- lib/dfe/analytics/send_events.rb
- lib/dfe/analytics/testing.rb
- lib/dfe/analytics/testing/helpers.rb
- spec/dfe/analytics/azure_federated_auth_spec.rb
- spec/dfe/analytics/big_query_api_spec.rb
- spec/dfe/analytics/big_query_legacy_api_spec.rb
- spec/dfe/analytics/load_entities_spec.rb
- spec/dfe/analytics/send_events_spec.rb
- spec/dfe/analytics_spec.rb
- spec/spec_helper.rb
Use workload identity federation as an alternative authentication for GCP.
For more details please see GCP documentation [here](https://cloud.google.com/iam/docs/workload-identity-federation). 
Configuration of workload identity federation with  Azure and links to the azure documentation can be found [here](https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#azure)
The steps involved for authentication are shown in the diagram below:
From the diagram, Step 4 is what we have to today with the API key - We go straight to step 4 with the API Key.
So with WIF weeliminate the API Key, but go through Steps 1-3 to get an service account impersonation access token -  This replaces the API Key.
This file:
[lib/dfe/analytics/azure_federated_auth.rb](https://github.com/DF …
> Add support for workload identity federation and consolidate GCP/BigQuery APIs into seperate classes

- lib/dfe/analytics/initialisation_events.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/initialisation_events_spec.rb
Fix the initialise event scheduling during the maintenance window. 
See trello ticket [here](https://trello.com/c/OLgfjgl9/1571-bq-assurance-bq-2-ensure-bigquery-tables-are-encrypted-with-customer-managed-encryption-key-cmek?filter=member:amaratwal1).
> Fix sending of initialisation events to respect maintenance window

- lib/dfe/analytics/testing.rb
Schools experience were seeing an error when running the test suite after upgrading to the latest version of dfe-analytics.
This addition should prevent other services from seeing the same error.
> Add big_query_api requires to testing.rb

- lib/dfe/analytics/tasks/import_entities.rake
When `enable_analytics` is `true` the `import_all_entities` rake task outputs a confusing message stating that it is not enabled, but nonetheless continues to perform the task:
```bash
$ bundle exec rails dfe:analytics:import_all_entities
DfE Analytics is not enabled - Ignoring import_all_entities
```
This fix should avoid some confusion for users! :)
> Fix import_all_entities rake task output

- lib/dfe/analytics/shared/service_pattern.rb
A reported issue by itt-mentor-services where our service pattern module was causing a conflict with their service pattern in their application https://github.com/DFE-Digital/dfe-analytics/issues/136
Adding in DfE::Analytics name-spacing into our service pattern module file is the likely fix.
> Fix for service pattern name spacing issue

- lib/dfe/analytics/fields.rb
When testing the validation that hidden_pii fields do not overlap analytics_pii fields I noticed that the validation method would error if either the allowlist_pii file were in any of these scenarios:
1. `shared:`
2. `shared: candidates:`
3. `shared: candidates: []`
rather than `shared: {}` which is explicitly empty. To avoid this I updated the following methods to:
```
def self.hidden_pii
DfE::Analytics.hidden_pii || {}
end
def self.allowlist_pii
DfE::Analytics.allowlist_pii || {}
end
```
and added in `next if fields.nil? || fields.empty?` to the overlap validation method
> Cover edge cases for validations

- lib/dfe/analytics.rb
- lib/dfe/analytics/event.rb
- lib/dfe/analytics/event_matcher.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics/event_matcher_spec.rb
- spec/dfe/analytics/send_events_spec.rb
This PR includes updates to the masking hidden_pii strategy
1. It removes masking_hidden_data method from the event_matcher as this isn't necessary for masking the logs
2. Updates the masking method, so instead of finding the hidden_pii fields per entity, it now just searches for the hidden_pii key/values in the logs
3. Updates to filter_matched? method to avoid exceptions
> Update log masking method

- README.md
- spec/dfe/analytics/event_spec.rb
This PR includes an update to the Readme and a event test to cover hidden_data being included in in a custom event
> Add reference to hidden_pii to cutom events

- README.md
- lib/dfe/analytics.rb
- lib/dfe/analytics/requests.rb
- spec/dfe/analytics/requests_spec.rb
Relates to [this ticket ](https://trello.com/c/URi1qr7E/1989-support-config-to-exclude-web-request-events-matching-a-string-or-regular-expression?filter=member:portererica)
Almost all services have had to find a work around to exclude the /healthcheck endpoint from being included as a web_request event. Currently there is no way of excluding this through the gem. 
This PR allows certain endpoints and paths to be excluded by allowing services to list these in their config file.
> Allow certain paths or endpoints to be excluded

- lib/dfe/analytics/entities.rb
- spec/dfe/analytics/entities_spec.rb
ECF reported that they were seeing a disparity between production db numbers and BigQuery arising during a transaction - the event is sending straight away so if the transaction ends up rolling back the analytics event has already been sent to BQ and doesn’t match the db
This PR updates the callbacks (after_create after_update and after_destroy) to be after_create_commit `after_update_commit and after_destroy_commit so that events will only send after the transaction is complete but also if it rolls back the event will not send`
ECF did some testing of this update:
The issue was initially detected in the method save_and_dedupe_participant https://github.com/DFE-Digital/early-careers-framework/blob/main/app/models/npq_application.rb#L134. I've tested the fix locally by using some …
> Update callbacks to have _commit suffix

- CHANGELOG.md
- Gemfile.lock
- lib/dfe/analytics/version.rb
- Resolve undefined method `migration_context` when upgrading to rails 7.2 [\#162](https://github.com/DFE-Digital/dfe-analytics/pull/162) ([avinhurry](https://github.com/avinhurry))
- Add workload identity federation docs [\#160](https://github.com/DFE-Digital/dfe-analytics/pull/160) ([asatwal](https://github.com/asatwal))
> release v1.14.1

- lib/dfe/analytics/services/entity_table_checks.rb
- lib/dfe/analytics/services/generic_checksum_calculator.rb
- lib/dfe/analytics/services/postgres_checksum_calculator.rb
- spec/dfe/analytics/services/entity_table_checks_spec.rb
- spec/dfe/analytics/services/generic_checksum_calculator_spec.rb
- spec/dfe/analytics/services/postgres_checksum_calculator_spec.rb
[Ticket](https://trello.com/c/F6HB3sf3/2099-investigate-rowcount-mismatches-on-findpub-and-teaching-vacancies)
Publish have a table "course_subjects" that has been long term out of sync with Big Query
Investigation showed this was because they have a number of records where updated_at is null and they were being excluded from the row_count during entity table check job / import entity rake task causing the row_count and checksum to not match
This is thought to apply to several other tables in Publish and to at least one other service
This PR updates:
1) the entity_table_check_job to firstly order by created_at if updated_at has null values, and finally to default to ID if updated_at/created_at are missing or have null values
2) the where clause to include order_by records with null values …
> Allow ordering by id if created_at/updated_at is null

- CHANGELOG.md
- Gemfile.lock
- lib/dfe/analytics/version.rb
- Allow ordering by id if created\_at/updated\_at is null [\#164](https://github.com/DFE-Digital/dfe-analytics/pull/164) ([ericaporter](https://github.com/ericaporter))
> release v1.14.2

- config/locales/en.yml
- lib/dfe/analytics.rb
- spec/dfe/analytics_spec.rb
This pull request introduces a config option to disable one or more models entirely:
```
proc { |x| x.to_s =~ /Namespace::/ } will exclude all
```
In my application, there were 2 models with very similar names: `Namespace::Foo` and `Foo`, pointing to table `foos` in 2 different databases. Because `dfe-analytics` does not recognize namespaces or different databases, the above option is a viable solution to the problem. The reason for similar models/tables is migration - one application data is moving to another.
> Config option to exclude models

- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
- spec/dfe/analytics/requests_spec.rb
The above having been stable for me for the from Friday to Monday pm, am happy to merge this in
> change remote_ip

- README.md
- lib/dfe/analytics/event.rb
- spec/dfe/analytics/event_spec.rb
[Trello Ticket](https://trello.com/c/LhJ0aFbv)
If any of your services is using dfe-analytics gem and pushing custom events into BigQ, you may want to check that all your custom events information is being pushed correctly into BigQ. We've recently discovered that the version v1.13 of the gem (released in July) introduced a breaking change that caused the contextual data on the existing event calls being lost since. As it just filters out the info, so no errors are raised.
Addresses the issue here: https://github.com/DFE-Digital/dfe-analytics/issues/182
> Breaking change on events with_data() method introduced with v1.13.0 release

- spec/dfe/analytics/entities_spec.rb
The transaction rollback tests seem to have been incorrectly configured, calling a create action outside of the transaction block, which results in a send event even when the block is rolled back.
> update transaction tests

- lib/dfe/analytics.rb
- lib/dfe/analytics/send_events.rb
- spec/dfe/analytics_spec.rb
We are rescuing initialisation and other errors with Rails.logger.info messages, which makes them difficult to find In the output logs. This PR updates the relevant info messages to error or warn level
> update error levels

- lib/dfe/analytics/api_requests.rb
Ensure API Request events always sent, event if there is an error code returned.
Trello tickets:
https://trello.com/c/bbU5kOXr
Changes proposed in this pull request
Add around_action callback for api_request event types with ensure block.
> Ensure API Request events always sent

- lib/dfe/analytics/services/entity_table_checks.rb
- lib/dfe/analytics/services/generic_checksum_calculator.rb
- lib/dfe/analytics/services/postgres_checksum_calculator.rb
- spec/dfe/analytics/send_events_spec.rb
- spec/dfe/analytics/services/entity_table_checks_spec.rb
We are getting chacksum mismatched where we have identical row counts but differing updated at values for various reasons. We have decided to remove the updated_at values from the checksum calculators.
I think this will also need to be matched in dataform
> rm updated_at in checksum calculators
